# Generated by Django 3.1 on 2020-08-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Object')),
                ('code', models.DecimalField(decimal_places=3, max_digits=6)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Request')),
                ('price', models.CharField(max_length=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Valve')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='quantity')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.request')),
            ],
        ),
        migrations.CreateModel(
            name='OtherObjectsInRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='quantity')),
                ('other_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.otherobject')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.request')),
            ],
        ),
        migrations.AddField(
            model_name='otherobject',
            name='request',
            field=models.ManyToManyField(through='one.OtherObjectsInRequest', to='one.Request', verbose_name='Object'),
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Motor')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='quantity')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.request')),
            ],
        ),
    ]
